-- Update refunds table status enum to match Java entity
-- Current: PENDING, APPROVED_WAITING_RETURN, RETURNING, APPROVED_REFUNDING, COMPLETED, REJECTED
-- New:     REQUESTED, APPROVED, REJECTED, COMPLETED

ALTER TABLE refunds 
MODIFY COLUMN status ENUM('REQUESTED', 'APPROVED', 'REJECTED', 'COMPLETED') 
DEFAULT 'REQUESTED';

-- Update existing data if any
UPDATE refunds SET status = 'REQUESTED' WHERE status = 'PENDING';
UPDATE refunds SET status = 'APPROVED' WHERE status IN ('APPROVED_WAITING_RETURN', 'RETURNING', 'APPROVED_REFUNDING');
